### ISSUE TITLE
gatsby build fails due to missing isBrowser check on isLoggedIn() method

### ISSUE THREAD

**Issue by ardiewen** [NeverNull/gatsby-apollo-wpgraphql-jwt-starter#3]
Hi all,

First of all, thank you so much for creating this starter as it is super helpful in establishing best practices on how to interact with authentication on WPGraphQL.

I noticed that when attempting to run the build script, the following error occurs:

```
  47 | 
  48 |   const isLoggedIn = () =>
> 49 |     getInMemoryAuthToken().authToken && !isTokenExpired(getInMemoryAuthToken().authToken)
     |                            ^
  50 | 
  51 |   useEffect(() => {
  52 |     if (isOnline && getRefreshToken()) {


  WebpackError: TypeError: Cannot read property 'authToken' of null
  
  - useAuth.js:49 Object.isLoggedIn
    src/hooks/useAuth.js:49:28
  
  - dashboard.js:23 Dashboard
    src/pages/dashboard.js:23:13
```

It appears that this can be remedied by importing `isBrowser` into useAuth.js and then making the following modification to the isLoggedIn method:

```
  const isLoggedIn = () =>
    isBrowser &&
    getInMemoryAuthToken().authToken &&
    !isTokenExpired(getInMemoryAuthToken().authToken)
```

This is also inline with how the gatsby tutorial approaches it:
```
export const isBrowser = () => typeof window !== "undefined"
export const getUser = () =>
  isBrowser() && window.localStorage.getItem("gatsbyUser")
    ? JSON.parse(window.localStorage.getItem("gatsbyUser"))
    : {}
```
https://www.gatsbyjs.org/tutorial/authentication-tutorial/

**Comment by henrikwirth** [comment]
Hi @ardiewen thanks for the feedback. I actually already fixed this in another project, just didn't have the time to apply the changes here. I'll try to add the changes at the end of the week.

**Comment by henrikwirth** [comment]
Couldn't help myself and fix it directly. I added the isBrowser on the getInMemoryAuthToken() instead and cleaned up some other stuff. check out the las commit ^^

Hope that fixes your problem, if not we can reopen this.
